global:
  scrape_interval: 15s
  external_labels:
    monitor: 'glm.h3po.de'

rule_files:
  - /prometheus/rules/recording/*.yml

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'golem-networkstats'
    static_configs:
      - targets: ['golem-networkstats-exporter:1234']

  - job_name: "coinmarketcap"
    static_configs:
      - targets: ["golem-coinmarketcap-exporter:9101"]

  - job_name: "grafana"
    static_configs:
      - targets: ["golem-grafana:3000"]