groups:
  - name: counts
    rules:
      - record: golem_count_provider_online_bool
        expr: golem_provider_online_bool
  - name: averages
    rules:
      - record: golem_avg_provider_earnings_GLM_total
        expr: avg(golem_provider_earnings_GLM_total)
      - record: golem_avg_provider_mem_bytes
        expr: avg(golem_provider_mem_bytes)
      - record: golem_avg_provider_cpu_threads
        expr: avg(golem_provider_cpu_threads)
      - record: golem_avg_provider_storage_bytes
        expr: avg(golem_provider_storage_bytes)
      - record: golem_avg_provider_price_start_GLM
        expr: avg(golem_provider_price_start_GLM)
      - record: golem_avg_provider_price_per_second_GLM
        expr: avg(golem_provider_price_per_second_GLM)
      - record: golem_avg_provider_price_per_cpu_second_GLM
        expr: avg(golem_provider_price_per_cpu_second_GLM)
  - name: means
    rules:
      - record: golem_mean_provider_earnings_GLM_total
        expr: quantile(0.5, golem_provider_earnings_GLM_total)
      - record: golem_mean_provider_mem_bytes
        expr: quantile(0.5, golem_provider_mem_bytes)
      - record: golem_mean_provider_cpu_threads
        expr: quantile(0.5, golem_provider_cpu_threads)
      - record: golem_mean_provider_storage_bytes
        expr: quantile(0.5, golem_provider_storage_bytes)
      - record: golem_mean_provider_price_start_GLM
        expr: quantile(0.5, golem_provider_price_start_GLM)
      - record: golem_mean_provider_price_per_second_GLM
        expr: quantile(0.5, golem_provider_price_per_second_GLM)
      - record: golem_mean_provider_price_per_cpu_second_GLM
        expr: quantile(0.5, golem_provider_price_per_cpu_second_GLM)

