groups:
  - name: counts
    rules:
      - record: golem_count_provider_online_bool
        expr: count(golem_provider_online_bool == 1) without (node_id)
  - name: averages
    rules:
      - record: golem_avg_provider_earnings_total
        expr: avg(golem_provider_earnings_total) without (node_id)
      - record: golem_avg_provider_mem_bytes
        expr: avg(golem_provider_mem_bytes) without (node_id)
      - record: golem_avg_provider_cpu_threads
        expr: avg(golem_provider_cpu_threads) without (node_id)
      - record: golem_avg_provider_storage_bytes
        expr: avg(golem_provider_storage_bytes) without (node_id)
      - record: golem_avg_provider_price_start
        expr: avg(golem_provider_price_start) without (node_id)
      - record: golem_avg_provider_price_per_second
        expr: avg(golem_provider_price_per_second) without (node_id)
      - record: golem_avg_provider_price_per_cpu_second
        expr: avg(golem_provider_price_per_cpu_second) without (node_id)
  - name: means
    rules:
      - record: golem_mean_provider_earnings_total
        expr: quantile(0.5, golem_provider_earnings_total) without (node_id)
      - record: golem_mean_provider_mem_bytes
        expr: quantile(0.5, golem_provider_mem_bytes) without (node_id)
      - record: golem_mean_provider_cpu_threads
        expr: quantile(0.5, golem_provider_cpu_threads) without (node_id)
      - record: golem_mean_provider_storage_bytes
        expr: quantile(0.5, golem_provider_storage_bytes) without (node_id)
      - record: golem_mean_provider_price_start
        expr: quantile(0.5, golem_provider_price_start) without (node_id)
      - record: golem_mean_provider_price_per_second
        expr: quantile(0.5, golem_provider_price_per_second) without (node_id)
      - record: golem_mean_provider_price_per_cpu_second
        expr: quantile(0.5, golem_provider_price_per_cpu_second) without (node_id)
  - name: sums
    rules:
      - record: golem_sum_provider_earnings_total
        expr: sum(golem_provider_earnings_total) without (node_id)
      - record: golem_sum_provider_mem_bytes
        expr: sum(golem_provider_mem_bytes) without (node_id)
      - record: golem_sum_provider_cpu_threads
        expr: sum(golem_provider_cpu_threads) without (node_id)
      - record: golem_sum_provider_storage_bytes
        expr: sum(golem_provider_storage_bytes) without (node_id)
      - record: golem_sum_provider_price_start
        expr: sum(golem_provider_price_start) without (node_id)
      - record: golem_sum_provider_price_per_second
        expr: sum(golem_provider_price_per_second) without (node_id)
      - record: golem_sum_provider_price_per_cpu_second
        expr: sum(golem_provider_price_per_cpu_second) without (node_id)